Convert json to rust
two-shots-later/vitruvian-vtt pull request #18
Opened 2024-08-24 14:09 UTC by Gearhartlove

Fixed issue #17

2024-08-24 16:02 UTC, Gearhartlove commented
Looks like I have some unintended changes, I'll fix this when I get a chance later today. The commit I want is this one: 3b97b15315becca5951dc3a2bf8795afaf0f331a

2024-08-24 18:11 UTC, MrVintage710 requested changes
Overall the code quality is great, we just need to organize it more to set a good presidant. let me know if you have any questions.

2024-08-24 18:11 UTC, MrVintage710 commented on src-tauri/src/classes.rs
This Code is good, however I think that we need to start with the right foot forward. This file should be divided into more than one file. It is managable right now, but as you add more types its going to get out of hand. Also put those files into a module that is descriptive of the code. Something like `pf2e_data_converter` or something like that.`janus` would be a cute and fun name for it because janus is the greek god of transportation and change. But that may be obscure. Also make sure to comment the stucts and functions of those structs. Here is a guide on that: https://doc.rust-lang.org/rust-by-example/meta/doc.html

2024-08-24 18:11 UTC, MrVintage710 commented on src-tauri/tests/classes.rs
Tests are good! However, I would avoid the pattern of one large test. If something goes wrong in that test, it will take a while to track it down. I would narrow down the test `should_write_and_read_to_db` to multiple tests like `inserting wizzard_to_db` and `reading_in_wizzard_from_pf2e`. Also these tests should be located in the module that I mentioned above.

2024-08-24 22:17 UTC, Gearhartlove commented on src-tauri/tests/classes.rs
I deleted these tests for now. I'm just keeping the `read_in_all_classes` test to test the serialization. My experiments with the DB before were good but in the wrong direction; we are going to have a much different entity/secondary-index schema so those 'tests' are not all that useful any more. 

When I start to insert / read from this db I'll make them smaller for sure. I think it's OK to have the serialization one be larger because there are a bunch of classes :sweat_smile:

2024-08-24 22:18 UTC, Gearhartlove commented on src-tauri/src/classes.rs
This is a good idea, I'll put some energy into organization & commenting next time I sit down to work on this.

2024-08-24 22:19 UTC, Gearhartlove commented on src-tauri/Cargo.toml
I didn't know you could do this, sweet! Updating now!

2024-08-24 23:22 UTC, Gearhartlove commented on src-tauri/src/classes.rs
Hey @MrVintage710 I organized the files more with /ingestion & /ingestion/classes /ingestion/core. The idea is that we will have important objects that we want to ingest like a class or item or monster; these will get their own ingestion logic (/ingestion/classes).  The similar properties like `description` & `publication` for example will be in /ingestion/core

2024-08-24 23:22 UTC, Gearhartlove commented on src-tauri/src/classes.rs
Thoughts on how it's layed out now? 

Note: I have not commented anything yet; if you want to wait for review that's understandable

2024-08-25 01:29 UTC, Gearhartlove commented on src-tauri/src/classes.rs
update: I'm continuing to work on this, I have some good ideas for organization that supports more than just Pf2e

2024-08-28 02:34 UTC, MrVintage710 approved these changes
This is good! Good work Kristoff 🎆

2024-08-28 02:49 UTC, merged