Adding Entities, Components for Backend
two-shots-later/vitruvian-vtt pull request #25
Opened 2024-09-03 03:01 UTC by MrVintage710

PR for #19

This PR will add the following:
- **Entities**. These are the base of our data system.
- **Components**. These are the parts of an entity that define what it is.
- **Archetypes**. This a describer that defines a set of components.

2024-09-03 03:36 UTC, Gearhartlove commented
:eyes: I'll take a look at this tomorrow, looks super promising!

2024-09-04 01:37 UTC, Gearhartlove commented
Last thing to note is that the 3 tests `src-types/src/entity.rs` pass perfectly. The doc tests however, above `impl Entity` in`fn add ...`, `fn get ...` , and `fn remove ...` do not work currently. When I run `cargo test` the main 3 tests fail and the other doc tests fail. 

This is not a major issue, but it is confusing when you run a `cargo test`. To fix this we need to 
- import correct dependencies in each doc test (I know repetitive :sweat_smile:)
- create structs for `A` and `B` for each doc test

2024-09-04 02:24 UTC, Gearhartlove requested changes
Here is my review! yay!

2024-09-04 02:29 UTC, MrVintage710 commented on src-types/src/entity.rs
> +    compnents : HashMap<TypeId, RefCell<Box<dyn Component>>>,
This naming was fixed!

2024-09-04 02:29 UTC, MrVintage710 commented on src-tauri/src/lib.rs
> +    println!("{}", bulk.to_json().as_str().unwrap())
I removed this as it was test code anyways. Problem solved!

2024-09-04 02:30 UTC, MrVintage710 commented on src-tauri/Cargo.lock
Yup! Its should be good from here on out

2024-09-04 02:33 UTC, Gearhartlove commented on src-tauri/Cargo.lock
We are git ignoring the Cargo.lock so we won't see this issue anymore :+1:

2024-09-04 02:39 UTC, Gearhartlove approved these changes

2024-09-04 02:39 UTC, merged